CREATE DATABASE customer_data;
USE customer_data;

-- Quick data preview
SELECT * FROM cleaned_data LIMIT 10;

-- Total revenue, average purchase amount and total transactions by product type
SELECT
    product_type,
    COUNT(*) AS total_transactions,
    ROUND(SUM(purchase_amount), 2) AS total_purchase_amount,
    ROUND(AVG(purchase_amount), 2) AS average_purchase_amount
FROM cleaned_data
GROUP BY product_type
ORDER BY total_purchase_amount DESC;

-- Total revenue generated by male vs female customers
SELECT 
    gender,
    COUNT(*) AS total_transactions,
    ROUND(SUM(purchase_amount), 2) AS total_revenue,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM cleaned_data
GROUP BY gender
ORDER BY total_revenue DESC;

-- Average review rating for all products
SELECT 
    item_purchased,
    COUNT(*) AS total_reviews,
    ROUND(AVG(review_rating), 2) AS average_review_rating
FROM cleaned_data
GROUP BY item_purchased
ORDER BY average_review_rating DESC;

-- Count of Customers who used discount and still purchased more than average purchase amount
SELECT 
    COUNT(*) AS high_spenders_with_discount,
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM cleaned_data 
    WHERE discount_applied = 'Yes'), 2) AS percentage_of_discount_users
FROM cleaned_data
WHERE discount_applied = 'Yes' 
AND purchase_amount > (SELECT AVG(purchase_amount) FROM cleaned_data);

-- Average purchase amount by shipping type
SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM cleaned_data
GROUP BY shipping_type
ORDER BY avg_purchase_amount DESC;

-- Which shipping type is most commonly used and does it vary by season
SELECT 
    season,
    shipping_type,
    COUNT(*) AS total_orders
FROM cleaned_data
GROUP BY season, shipping_type
ORDER BY season, total_orders DESC;

-- Relationship between shipping type and review rating
SELECT 
    shipping_type,
    COUNT(*) AS total_orders,
    ROUND(AVG(review_rating), 2) AS avg_review_rating
FROM cleaned_data
GROUP BY shipping_type
ORDER BY avg_review_rating DESC;

-- Top 5 products with highest percentage of purchases with discount applied
SELECT 
    item_purchased,
    COUNT(*) AS total_purchases,
    SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discounted_purchases,
    ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS discount_rate
FROM cleaned_data
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Segment customers into New, Returning and Loyal based on previous purchases
SELECT 
    CASE 
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 9 THEN 'Returning'
        WHEN previous_purchases >= 10 THEN 'Loyal'
    END AS customer_segment,
    COUNT(customer_id) AS customer_count
FROM cleaned_data
GROUP BY customer_segment
ORDER BY customer_count DESC;

-- Calculate average and total purchase amount by customer segment
SELECT 
    CASE 
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 9 THEN 'Returning'
        WHEN previous_purchases >= 10 THEN 'Loyal'
    END AS customer_segment,
    AVG(purchase_amount) AS avg_purchase_amount,
    Round(SUM(purchase_amount),2) AS total_purchase_amount
FROM cleaned_data
GROUP BY customer_segment
ORDER BY avg_purchase_amount DESC;

-- Top 2 most purchased products within each category
WITH item_count AS (
    SELECT 
        product_type,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY product_type 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM cleaned_data
    GROUP BY product_type, item_purchased
)
SELECT 
    item_rank,
    product_type,
    item_purchased,
    total_orders
FROM item_count
WHERE item_rank <= 2
ORDER BY product_type, item_rank;

-- Are repeat buyers more likely to subscribe
SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers,
    ROUND(COUNT(customer_id) * 100.0 / SUM(COUNT(customer_id)) OVER(), 2) AS percentage
FROM cleaned_data
WHERE previous_purchases > 5
GROUP BY subscription_status
ORDER BY repeat_buyers DESC;

-- Most preferred payment method by customers
SELECT payment_method,
    COUNT(*) AS total_transactions,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM cleaned_data
GROUP BY payment_method
ORDER BY total_transactions DESC;

-- Top 10 locations by revenue
SELECT location,
    COUNT(*) AS total_customers,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM cleaned_data
GROUP BY location
ORDER BY total_revenue DESC
LIMIT 10;


-- Revenue contribution of each age group
SELECT 
    age_group,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM cleaned_data
GROUP BY age_group
ORDER BY total_revenue DESC;

-- Revenue and discount behavior across seasons
SELECT 
    season,
    COUNT(*) AS total_orders,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS discount_rate,
    ROUND(AVG(review_rating), 2) AS avg_rating
FROM cleaned_data
GROUP BY season
ORDER BY FIELD(season, 'Spring', 'Summer', 'Fall', 'Winter');

